### ISSUE TITLE
should check chrome.manifest

### ISSUE THREAD

**Issue by foudfou** [daveschaefer/checkloc#4]
checklock should check for `locale` entries in `chrome.manifest`.
BabelZilla does that.
It may be a good idea to see with BabeZilla folks what else can be ported from their system too.

**Comment by daveschaefer** [comment]
Hey @foudfou , good suggestion. I was also looking at this. I have indeed posted on Babelzilla and the response seems positive, so we'll see.

I believe we could inspect `chrome.manifest` and `install.rdf` and add tests for the following things:
* check every `chrome.manifest` entry to make sure a matching locale folder exists on disk
* check if every locale folder has a matching entry in `chrome.manifest`
* check if the locales listed in `chrome.locale` are valid known Mozilla locale codes
* check that `install.rdf` is valid XML
* check every `install.rdf` locale entry to make sure a matching locale folder exists on disk
* check if every locale folder has a matching entry in `install.rdf`
* check if the locales listed in `install.rdf` are valid known Mozilla locale codes

Are there other tests you were thinking of?

I also found [this Babelzilla wiki page](http://babelwiki.babelzilla.org/index.php?title=GoofyPlan_for_an_extension_testing_machine) with some similar ideas.


When you say "BabelZilla does that" - is there an existing tool that does this? Or do you mean the Babelzilla Web Translation System itself?

**Comment by foudfou** [comment]
I meant: the BabelZilla WTS does that. Great to hear they are willing to share.
I think you covered the cases pretty well.

**Comment by daveschaefer** [comment]
Just to give you an update: the coding is going well and I'm almost finished. Just need to do a bit more testing and review before uploading. I will likely have the update released within a week, but at most two weeks.

Through testing I also discovered another test case: we can make sure that no locale entry is defined more than once inside `chrome.manifest` or `install.rdf` (e.g. don't allow two locale entries for german). If you install an extension with locale entries defined more than once, the later entries simply overwrite the earlier ones. We'd definitely want to catch that.

**Comment by daveschaefer** [comment]
@foudfou Okay, the new code has been released :) Give this a shot and see how it works for you. Let me know what you think.

**Comment by foudfou** [comment]
* I'm unsure for `localecodes.py`: it lists the locale *teams*. Shouldn't it be a combination (function maybe) of [codes](https://wiki.mozilla.org/L10n:Locale_Codes).
For ex. I get warnings for *de-DE* or *hr-HR* which are valid, although general *de* or *hr* locales seem to be used in practice...
* I couldn't find a better reference than https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_extension_descriptions, but I don't think a *us-EN* description is necessary in `install.rdf`. Maybe the warning could be an `INFO`.

**Comment by daveschaefer** [comment]
Yeah, I would be happy to update the list with a better set of codes if we can find a better set or reference.

Searching around I found these URLs in firefox:
chrome://global/locale/languageNames.properties
chrome://global/locale/regionNames.properties

But we'd need to know which ones were possible valid combinations.
I suppose we could always just check the first two digits for the language. Perhaps there are regions we don't know about. But it would be great if we could solve the issue properly.

How about the rest of the script - do the rest of the tests work for you?

**Comment by foudfou** [comment]
Don't know if a list of valid combination exists. Maybe check with localization guys on the Mozilla IRC.
Yes the rest seems to run fine.

**Comment by daveschaefer** [comment]
Posted to the loc list and currently discussing it. One person mentioned this link - https://svn.mozilla.org/libs/product-details/json/languages.json 

That file contains both de-DE and hr-HR.
I found the extension [Flagfox](https://addons.mozilla.org/en-US/firefox/addon/flagfox/), which has 36 locales, including e.g. uk-UA. I don't see uk-UA in the languages.json list, so we may just have to keep an eye out and maintain a custom list.

I'll keep digging.

Since the script now checks chrome.manifest. how about I create a new ticket for getting the right list of locales, and close this ticket, since its request is complete. Sound good?

**Comment by foudfou** [comment]
Fine for me.

**Comment by daveschaefer** [comment]
I created #8 to update the locale list. It may happen in two parts. Closing this ticket as we now parse and check the contents of manifest files.

**Comment by daveschaefer** [comment]
@foudfou The list of locale codes has been updated and I have released version 1.3.1. Let me know what you think. The ticket #8 tracks that issue.
