### ISSUE TITLE
Handle subfolders between 'chrome' and 'locale'

### ISSUE THREAD

**Issue by daveschaefer** [daveschaefer/checkloc#7]
Some extensions - such as [flagfox](https://addons.mozilla.org/en-US/firefox/addon/flagfox/) use a subfolder between their 'chrome' folder and their 'locale' folder. The script should be able to deal with this and find the correct parent or child folder.

e.g. flagfox uses the path `chrome/flagfox/locale`

**Comment by daveschaefer** [comment]
I believe the proper fix for this is to change the checkloc script interface. Rather than pointing it to the locale folders and then working backwards to try and find manifest files, we should simply point the script to the location of the `chrome.manifest` file. The script can then read all of the location information from that file, and find the right/expected folders to parse. If locale folders are not found in
the specified location, that is an error, as the browser will do the same thing when the extension is installed.


Such a change would be easiest if we break backwards compatibility, as the new script would behave in a different way. But, since checkloc currently has a small number of users hopefully that will be okay, as the new interface lets us build a more more stable, scalable, and maintainable script.

**Comment by daveschaefer** [comment]
We would still want a flag to parse individual locale folders and not check the manifest files, so we could run the unit tests and for anyone that might want to do this. We should likely rename and refactor the --no-manifest switch to this.

**Comment by daveschaefer** [comment]
@foudfou - Hey foudfou, would you be willing to give me your thoughts on this proposed change? Would it help or hurt you if checkloc were changed and you had to point it at the 'chrome.manifest' file rather than pointing it at the local folders? As you are currently my most outspoken customer (and thanks! ;) I am very interested to know what you think.

**Comment by foudfou** [comment]
I think this is the correct approach. Locales are defined in 2 places I think: `chrome.manifest` and `install.rdf`.
I happened to forget to declare new locales in `chrome.manifest` for instance. And I don't know if they were taken into account by the application.
You should double-check with the BabelZilla algorithm too. Because they detect these cases (orphan locale folders).
To sum up: parse `chrome.manifest` and `install.rdf`, and also look for subfolders in `locale/` that look like locale folders.

**Comment by daveschaefer** [comment]
@foudfou Thanks for the confirmation! I will compare notes with Babelzilla. I look forward to the improved behaviour.

**Comment by daveschaefer** [comment]
This has now been implemented! The version has been increased to 2.0 to reflect that the script now uses a different interface.

I have been chatting with the kind folks and Babelzilla and they are happy to see this behaviour :)
