### ISSUE TITLE
Correct locale list

### ISSUE THREAD

**Issue by daveschaefer** [daveschaefer/checkloc#8]
The current locale list isn't correct - it's closer to the group of local *groups* used by Mozilla. Find a better list.

**Comment by daveschaefer** [comment]
This has been started in version 1.3.1. Created initial list based on https://svn.mozilla.org/libs/product-details/json/languages.json , and added several locales used by actual extensions in the wild.

We should be able to close this ticket for now but there is still room for improvement. I am investigating two more leads.

**Comment by daveschaefer** [comment]
@foudfou How does this new list look to you?

**Comment by foudfou** [comment]
@daveschaefer looks fine. I think you can refine later, if/when the need arises.

**Comment by daveschaefer** [comment]
@foudfou Yep, that is the plan :) Thanks!
